owner: sasachan # GitHub username
repo: x-experiment-uptime # GitHub repository name
sites: # List of endpoints to track
  - name: NST
    url: https://www.neosofttech.com/
assignees: # Users to assign downtime issues (optional)
  - sasachan
status-website: # Status website (optional)
  baseUrl: /x-experiment-uptime
  name: Upptime # Status website title
